#!/usr/bin/env python3
"""qa/<name>.txt -> src/qa/qa_script.inc

Lines:  at FRAME press A[+B..] [hold N]
        at FRAME stick X Y [hold N]       (X, Y in -80..80; up is +Y)
        at FRAME cstick X Y [hold N]
        mode ui                           (menus only: no move sweep, the CSS stays up)
"""
import sys
from pathlib import Path

PAD = dict(LEFT=0x1, RIGHT=0x2, DOWN=0x4, UP=0x8, Z=0x10, R=0x20, L=0x40,
           A=0x100, B=0x200, X=0x400, Y=0x800, START=0x1000)


def main(src, dst):
    rows = []
    ui = 0
    for line in Path(src).read_text().splitlines():
        p = line.split('#')[0].split()
        if not p:
            continue
        if p == ['mode', 'ui']:  # menus only: the sweep stays off, the CSS stays up
            ui = 1
            continue
        at = int(p[1]); hold = int(p[p.index('hold') + 1]) if 'hold' in p else 6
        b = x = y = cx = cy = 0
        if p[2] == 'press':
            for k in p[3].split('+'):
                b |= PAD[k.upper()]
        elif p[2] == 'stick':
            x, y = int(p[3]), int(p[4])
        elif p[2] == 'cstick':
            cx, cy = int(p[3]), int(p[4])
        rows.append((at, at + hold, b, x, y, cx, cy))
    end = max((r[1] for r in rows), default=0)
    out = ['/* generated by tools/qa/script.py from %s */' % Path(src).name,
           'static const QaStep qa_script[] = {']
    out += ['    { %d, %d, 0x%X, %d, %d, %d, %d },' % r for r in rows] or ['    { 0, 0, 0, 0, 0, 0, 0 },']
    out += ['};', '#define QA_SCRIPT_LEN %d' % max(len(rows), 1), '#define QA_SCRIPT_END %d' % end,
            '#define QA_SCRIPT_UI %d' % ui, '']
    Path(dst).write_text('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
